// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASc4spsjv20HGVUcybaz7HjCs8ZwAbsbg',
    appId: '1:662118066081:web:a5dcb52eaaf1b91d06cde0',
    messagingSenderId: '662118066081',
    projectId: 'x-buddy',
    authDomain: 'x-buddy.firebaseapp.com',
    storageBucket: 'x-buddy.appspot.com',
    measurementId: 'G-D6B3XJJT06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakIpS_9z5euiNRFsr6BN1VIzHT-joYXw',
    appId: '1:662118066081:android:ba486b28188665ff06cde0',
    messagingSenderId: '662118066081',
    projectId: 'x-buddy',
    storageBucket: 'x-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATWNmN6nur6BMeWbMdmDf-8Pu1CYamjQ8',
    appId: '1:662118066081:ios:977db5d8413b2c1806cde0',
    messagingSenderId: '662118066081',
    projectId: 'x-buddy',
    storageBucket: 'x-buddy.appspot.com',
    iosBundleId: 'com.zephyrus.xBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATWNmN6nur6BMeWbMdmDf-8Pu1CYamjQ8',
    appId: '1:662118066081:ios:977db5d8413b2c1806cde0',
    messagingSenderId: '662118066081',
    projectId: 'x-buddy',
    storageBucket: 'x-buddy.appspot.com',
    iosBundleId: 'com.zephyrus.xBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASc4spsjv20HGVUcybaz7HjCs8ZwAbsbg',
    appId: '1:662118066081:web:258cd1b2e946c25e06cde0',
    messagingSenderId: '662118066081',
    projectId: 'x-buddy',
    authDomain: 'x-buddy.firebaseapp.com',
    storageBucket: 'x-buddy.appspot.com',
    measurementId: 'G-SZSD3X3T0Y',
  );
}
